M48
; DRILL file KiCad 10.0.5 date 2026-08-12T23:59:53
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-12T23:59:53+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X32.11Y-88.72
X37.89Y-88.72
T2
X5.0Y-5.0
X5.0Y-90.0
X145.0Y-5.0
X145.0Y-90.0
M30
