M48
; DRILL file KiCad 10.0.5 date 2026-08-11T15:40:55
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-11T15:40:55+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X17.11Y-78.72
X22.89Y-78.72
T2
X5.0Y-5.0
X5.0Y-80.0
X115.0Y-5.0
X115.0Y-80.0
M30
