#!/usr/bin/env python3
"""Generate the deterministic compressed firmware dashboard include."""

from __future__ import annotations

import argparse
import gzip
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src" / "dashboard.html"
OUTPUT = ROOT / "src" / "generated" / "dashboard_html_gz.h"


def render(source: bytes) -> str:
    payload = gzip.compress(source, compresslevel=9, mtime=0)
    rows = []
    for offset in range(0, len(payload), 16):
        chunk = payload[offset : offset + 16]
        rows.append("    " + ", ".join(f"0x{byte:02x}" for byte in chunk) + ",")
    return "\n".join([
        "// Generated by scripts/generate_dashboard.py; do not edit.",
        "// Source: src/dashboard.html",
        "#pragma once",
        "",
        "static const uint8_t DASHBOARD_HTML_GZ[] PROGMEM = {",
        *rows,
        "};",
        f"static constexpr size_t DASHBOARD_HTML_GZ_LEN = {len(payload)};",
        "",
    ])


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail when the generated include is stale")
    args = parser.parse_args()

    generated = render(SOURCE.read_bytes())
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != generated:
            raise SystemExit("[FAIL] dashboard include is stale; run python scripts/generate_dashboard.py")
        print(f"[PASS] dashboard include matches {SOURCE}")
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generated, encoding="utf-8", newline="\n")
    print(f"[OK] generated {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
